# version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: blog-php
    volumes:
      - .:/var/www/html
    # environment:
    #   DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"

  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: blog-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      # - ./public:/var/www/html
      # - ./vendor:/var/www/vendor
      # - ./.env:/var/www/.env
      # - ./src:/var/www/src
    depends_on:
      - php


  bd:
    image: mariadb:10.6
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # Interface web de Mailpit
      - "1025:1025" # Port SMTP pour envoyer des emails

  node:
    image: node:18
    container_name: blog-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && tail -f /dev/null"

volumes:
  db_data:
  apache_data:
