# version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: blog-php
    volumes:
      - .:/var/www/html
    # environment:
    #   DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"

  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: blog-apache
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - php


  bd:
    image: mariadb:10.6
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
  apache_data:
