<?php

namespace ContainerHKlmTFl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QtAFA7VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QtAFA7V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QtAFA7V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'categorie' => ['privates', '.errored..service_locator.QtAFA7V.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.QtAFA7V": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'categorie' => 'App\\Entity\\Categorie',
        ]);
    }
}
