<?php

namespace ContainerDTstjhv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CKQJI6dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cKQJI6d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cKQJI6d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\ArticleController::delete' => ['privates', '.service_locator.zwPUnYq', 'get_ServiceLocator_ZwPUnYqService', true],
            'App\\Controller\\Admin\\ArticleController::edit' => ['privates', '.service_locator.zwPUnYq', 'get_ServiceLocator_ZwPUnYqService', true],
            'App\\Controller\\Admin\\ArticleController::index' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\Admin\\ArticleController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController::delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\Admin\\CategorieController::edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\Admin\\CategorieController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\Admin\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController::show' => ['privates', '.service_locator.QtAFA7V', 'get_ServiceLocator_QtAFA7VService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.QtAFA7V', 'get_ServiceLocator_QtAFA7VService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.pC.MaYQ', 'get_ServiceLocator_PC_MaYQService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.Zkrc2qS', 'get_ServiceLocator_Zkrc2qSService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\ArticleController:delete' => ['privates', '.service_locator.zwPUnYq', 'get_ServiceLocator_ZwPUnYqService', true],
            'App\\Controller\\Admin\\ArticleController:edit' => ['privates', '.service_locator.zwPUnYq', 'get_ServiceLocator_ZwPUnYqService', true],
            'App\\Controller\\Admin\\ArticleController:index' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\Admin\\ArticleController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController:delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\Admin\\CategorieController:edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\Admin\\CategorieController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\Admin\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\CategorieController:show' => ['privates', '.service_locator.QtAFA7V', 'get_ServiceLocator_QtAFA7VService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.QtAFA7V', 'get_ServiceLocator_QtAFA7VService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.pC.MaYQ', 'get_ServiceLocator_PC_MaYQService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.Zkrc2qS', 'get_ServiceLocator_Zkrc2qSService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\ArticleController::delete' => '?',
            'App\\Controller\\Admin\\ArticleController::edit' => '?',
            'App\\Controller\\Admin\\ArticleController::index' => '?',
            'App\\Controller\\Admin\\ArticleController::new' => '?',
            'App\\Controller\\Admin\\CategorieController::delete' => '?',
            'App\\Controller\\Admin\\CategorieController::edit' => '?',
            'App\\Controller\\Admin\\CategorieController::index' => '?',
            'App\\Controller\\Admin\\CategorieController::new' => '?',
            'App\\Controller\\Admin\\CategorieController::show' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\ArticleController:delete' => '?',
            'App\\Controller\\Admin\\ArticleController:edit' => '?',
            'App\\Controller\\Admin\\ArticleController:index' => '?',
            'App\\Controller\\Admin\\ArticleController:new' => '?',
            'App\\Controller\\Admin\\CategorieController:delete' => '?',
            'App\\Controller\\Admin\\CategorieController:edit' => '?',
            'App\\Controller\\Admin\\CategorieController:index' => '?',
            'App\\Controller\\Admin\\CategorieController:new' => '?',
            'App\\Controller\\Admin\\CategorieController:show' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
