<?php

namespace ContainerDTstjhv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailNotificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Notification\MailNotification' shared autowired service.
     *
     * @return \App\Notification\MailNotification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Notification/MailNotification.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Notification\\MailNotification'])) {
            return $container->privates['App\\Notification\\MailNotification'];
        }
        $b = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Notification\\MailNotification'])) {
            return $container->privates['App\\Notification\\MailNotification'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Notification\\MailNotification'])) {
            return $container->privates['App\\Notification\\MailNotification'];
        }

        return $container->privates['App\\Notification\\MailNotification'] = new \App\Notification\MailNotification(new \Symfony\Component\Mailer\Mailer($a, $b, $c));
    }
}
