<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDTstjhv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDTstjhv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDTstjhv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDTstjhv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDTstjhv\App_KernelDevDebugContainer([
    'container.build_hash' => 'DTstjhv',
    'container.build_id' => 'b71a69bd',
    'container.build_time' => 1745491936,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDTstjhv');
